name: Deployment
on:
  push:
    branches:
      - main
      - dev
      - master # FIX: Added master so it triggers when you git push master

env: 
  MONGODB_DB_NAME: gha-demo
  MONGODB_CLUSTER_ADDRESS: cluster0.oqvi2em.mongodb.net
  MONGODB_USERNAME: Sujith
  MONGODB_PASSWORD: Suji123
  PORT: 8080

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
        
      - name: Cache dependencies
        uses: actions/cache@v4
        with:
          path: ~/.npm
          key: npm-deps-${{ hashFiles('**/package-lock.json') }}
          
      - name: Install dependencies
        run: npm ci
        
      - name: Run server
        run: |
          npm start & 
          npx wait-on http://127.0.0.1:${{ env.PORT }}
          
      - name: Run tests
        run: npm test
        
      - name: Output information
        run: echo "MONGODB_USERNAME:${{ env.MONGODB_USERNAME }}"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "MONGODB_USERNAME: ${{ env.MONGODB_USERNAME }}"
          echo "MONGODB_DB_NAME: ${{ env.MONGODB_DB_NAME }}"